1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:

import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose the array)
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)

Original Array:
[[38 37 81]
 [82 89 71]
 [84  6 19]]

Transposed Array:
[[38 82 84]
 [37 89  6]
 [81 71 19]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:

import numpy as np

# Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)
print("Original 1D Array:")
print(arr)

# Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped 2x5 Array:")
print(arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped 5x2 Array:")
print(arr_5x2)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:

import numpy as np

# Create a 4x4 NumPy array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Add a border of zeros around the array, resulting in a 6x6 array
bordered_arr = np.pad(arr, 1, mode='constant')
print("\nBordered 6x6 Array:")
print(bordered_arr)

Original 4x4 Array:
[[0.27020198 0.05566853 0.57849357 0.04565352]
 [0.17060919 0.21415749 0.91160084 0.664658  ]
 [0.1062777  0.23643615 0.23490612 0.20297706]
 [0.05554198 0.86578937 0.52579142 0.9854154 ]]

Bordered 6x6 Array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.27020198 0.05566853 0.57849357 0.04565352 0.        ]
 [0.         0.17060919 0.21415749 0.91160084 0.664658   0.        ]
 [0.         0.1062777  0.23643615 0.23490612 0.20297706 0.        ]
 [0.         0.05554198 0.86578937 0.52579142 0.9854154  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Create a NumPy array of words
words = np.array(['apple', 'banana', 'cherry'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print(spaced_words)

['a p p l e' 'b a n a n a' 'c h e r r y']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2
print("Addition:\n", addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("Subtraction:\n", subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("Multiplication:\n", multiplication)

# Perform element-wise division
division = array1 / array2
print("Division:\n", division)

Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [ ]:
import numpy as np

def is_prime(num):
  if num <= 1:
    return False
  if num <= 3:
    return True
  if num % 2 == 0 or num % 3 == 0:
    return False
  i = 5
  while i * i <= num:
    if num % i == 0 or num % (i + 2) == 0:
      return False
    i += 6
  return True

# Generate a NumPy array of 100 random integers
random_array = np.random.randint(0, 1001, 100)

# Find prime numbers
prime_numbers = np.extract(np.vectorize(is_prime)(random_array), random_array)

print("Random Array:", random_array)
print("Prime Numbers:", prime_numbers)

Random Array: [125 944 111 575 363  39 493 514 488 350 839 380 917 612 738 288 495 350
 200 538 948 500  28 876  93 364 385 300 547 248 462   9 183 656  33 999
 477 238 208 237 805 621 959 308 379 418 286 928 597 536 777 469 336 437
 257 380 958 337 189 120 788  66 293 362 358 107  74 560 258 767   9 777
 699 397 623 720 805 679 744 403 102 249 571 333 683 708 744 281 418 342
 610 641 682 177 805 670 731  88 761 152]
Prime Numbers: [839 547 379 257 337 293 107 397 571 683 281 641 761]
