In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
#enhance Python's capabilities for numerical operations?

ANS = NumPy (Numerical Python) is a  llibrary for working with arrays and mathematical operation in pythan
.its purpose is to provide support for large,multi-dimensional arrays and matrices,and to provide a wide range
og high-performance mathmatical function to manipulate them.

#advantage of numpy:

#1.efficient data storage and manipulation:
Numpy arrays are more memoey-efficient and faster to manipulate than pythan lists.
#2.vectorized operation:
numpy allows for element-wise operation on entire arrays,making it much faster thanusing pythan loops.
#3.matrix operation:
numpy provide an efficient way to perform matrix  multiplications,eigenvalue decomposition and other 
linear algebra operation.
#4random number generation:
numpy provide a robust random number generator.
#5.interoperability:
numpy arrays can be easily converted to and from other formats,such as pandas dataframes or scipy 
sparse marrices.

ENHANCEMENTS TO PYTHONS CAPABILITIES:
    
#SPEED:
numoy operation are much faster than equivalent python code.
#convenience:
numpy provides a simple and intutive API for numerical operation.
#3.functionally:
numpy adds supports for advanced mathmatical function and operation not available in pythan.

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
#other?

ANS = np.mean() nad np.average() are both used to calcultae the average of an array in numpy. however
there are subtle difference between them:
    #np.mean():
1.computes the arithmetic mean of the array elements.
2.ignoes NaN (not a number) values by default.
3.can be used iwth multi-dimensional arrays , in which case it computes the mean along the specified axis.
    #np.average():
1. computes the weighted average of the array elements.
2.allows for specifying weights for each element.
3.can handle NaN values by using the weights parameter.
4.can be used with multi-dimensional arrays,similar to np.mean()
 #when to use over the other:
        -you need the simple arithmetic mean.
        -youre working with multi-dimensional arrays and want to compute the mean along a specific axis.
#2
np.average() when:
    -you need a weighted average.
    -you want handle NaN values explicitly.
    -ypu need more control over the averaging process.

In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
#arrays.


NumPy provides several methods to reverse an array along different axes:

1. np.flip(): Reverses the array along the specified axis.

2. np.flipud(): Reverses the array along the vertical axis (axis 0).

3. np.fliplr(): Reverses the array along the horizontal axis (axis 1).

4. array[::-1]: Reverses the entire array.

Examples:

1D Array:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(np.flip(arr))  # Output: [5 4 3 2 1]
print(arr[::-1])  # Output: [5 4 3 2 1]


2D Array:


arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flip(arr, axis=0))  # Output: [[4 5 6], [1 2 3]]
print(np.flip(arr, axis=1))  # Output: [[3 2 1], [6 5 4]]
print(np.flipud(arr))  # Output: [[4 5 6], [1 2 3]]
print(np.fliplr(arr))  # Output: [[3 2 1], [6 5 4]]


In the 2D array examples:

- axis=0 reverses the rows (vertical axis).
- axis=1 reverses the columns (horizontal axis).
- np.flipud() reverses the rows.
- np.fliplr() reverses the columns.

In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
#in memory management and performance.


ANS = To determine the data type of elements in a numpy array,you can use the dtype attributes of the array:
    #import numpy as np
    #arr = np.array([1,2,3,4,5])
    #print(arr.dtype) #output:int32
Data types are crucial in memory mangement aand perfiormance for several reasons:
    1.memory usage:
        defferent data types require varying amounts of memory.for example,int32 takes 4 bytes,while 
        float64 takes 8 bytes.using the appropriate data type can help reduce memory usage.
    2.performance:
        certain operation are optimized specific data types. for instance ,integers operation are generally faster
        than floating-point operation.
    3.type conversion:
        when performing operation on arrays with different data types,numpy may need to perform type
        conversion,which can lead to performance overhead and memory usages.
    4.memory alignment:
        proper data type alignment can improve memoey access pattern,leading to better performance.
    5.compartibility:
        ensuring consistent data types can facilitate interoperability with other libraries and languages.
To optimize memoey mangement and performance:
    1.use the most appropriate data type fior your data.
    2.be mindful of type conversion and try to minimize them.
    3.use numpys data type specification

In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ANS = numpys ndarry(n-dimensional array) is a multi-dimensional array object,which is the core data
structure in numpy.its key features include:
    1.multi-dimensionality:
        ndarray can have any number of dimension from ID  to nD.
    2.Homogeneous data types:
        All elements in an udarray must have the same data type.
    3.fixed size:
        The size of an ndarray is fixed creation and cannot be changed.
    4.memory efficiency:
        ndarry stores data in a contiguous block of memoey,making it more memoey-efficient than pythaon lists.
    5.vectrizes operation:
        ndarray supports vectorized operation,allowing for efficient elements-wise operation.
    6.indexing and slicing:
        ndarray supports advanced indexing and slicing capabilities.
campared to standard python lists:
    1.data types flexibility:
        python lists can store elements of differenrt data types,whereeas ndarray requires a homogeneouus data type.
    2.dynamic size:
        python lists can grow or shrink dynamically,whereas has a fixed size.
    3.memory usages:
        python lists typicallty consume more memory than ndarray due to their dynamic nature and overhead.
    4.performance:
        undarray is optimized for numrical computations and provides faster perfirmance than pythan lists
        datasets.

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.



NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

1. Vectorized operations: NumPy arrays enable vectorized operations, allowing for element-wise computations without explicit loops, 
leading to massive speedups.

2. Memory efficiency: NumPy arrays store data in a contiguous block of memory, reducing memory overhead and improving cache locality.

3. Homogeneous data type: NumPy arrays require a homogeneous data type, allowing for optimized storage and computation.

4. Compiled C code: NumPy's core operations are implemented in compiled C code, providing a significant speed boost.

5. Parallelization: NumPy arrays can be easily parallelized, taking advantage of multi-core processors.

6. Optimized algorithms: NumPy implements optimized algorithms for various numerical operations, such as matrix multiplication and linear algebra.

7. Reduced overhead: NumPy arrays have reduced overhead compared to Python lists, which have overhead due to dynamic typing and resizing.

For large-scale numerical operations, NumPy arrays can be 10-100x faster than Python lists. This is particularly important 
in scientific computing, data analysis, and machine learning, where performance is critical.

Here's a simple example demonstrating the performance difference:


import numpy as np
import time

# Create a large Python list and NumPy array
python_list = list(range(1000000))
numpy_array = np.arange(1000000)

# Measure the time taken for element-wise multiplication
start_time = time.time()
result_list = [x * x for x in python_list]
print("Python list time:", time.time() - start_time)

start_time = time.time()
result_array = numpy_array * numpy_array
print("NumPy array time:", time.time() - start_time)

In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
#output.


NumPy's vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

vstack()

- Stacks arrays vertically (row-wise)
- Increases the number of rows
- Example:


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
# Output:
# [[1 2 3]
#  [4 5 6]]


hstack()

- Stacks arrays horizontally (column-wise)
- Increases the number of columns
- Example:


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))
# Output:
# [1 2 3 4 5 6]

In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
#array dimensions.

NumPy's fliplr() and flipud() methods are used to flip arrays horizontally (left-right) and vertically (up-down), respectively.

fliplr():

- Flips the array horizontally (left-right)
- Reverses the order of columns
- Does not change the number of rows

Example:


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.fliplr(arr))
# Output:
# [[3 2 1]
#  [6 5 4]]


flipud():

- Flips the array vertically (up-down)
- Reverses the order of rows
- Does not change the number of columns

Example:


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.flipud(arr))
# Output:
# [[4 5 6]
#  [1 2 3]]


Effects on various array dimensions:

- 1D array: fliplr() is equivalent to flipud(), as there's only one dimension to flip.
- 2D array:
    - fliplr() flips columns.
    - flipud() flips rows.
- 3D array or higher:
    - fliplr() flips the last dimension (columns).
    - flipud() flips the first dimension (rows)

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?



The array_split() method in NumPy splits an array into multiple sub-arrays along a specified axis. It takes three arguments:

1. ary: The input array to be split.
2. indices_or_sections: The number of splits or the indices at which to split.
3. axis: The axis along which to split (default is 0).

If indices_or_sections is an integer, the array is split into equal-sized sub-arrays. 
If it's a list of integers, the array is split at those specific indices.

Handling uneven splits:

- If the array cannot be evenly split, array_split() will adjust the size of the 
last sub-array to accommodate the remaining elements.
- If indices_or_sections is a list of integers, the splits will be made at those exact indices, regardless 
of whether the splits are even or uneven.

In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
#operations?



Vectorization and broadcasting are two fundamental concepts in NumPy that enable efficient array operations.

Vectorization:

Vectorization refers to the ability to perform operations on entire arrays at once, without the need for explicit loops. This is achieved by using NumPy's universal functions (ufuncs), which are designed to work with arrays. Vectorization allows for:

- Element-wise operations
- Matrix multiplication
- Array-wide reductions (e.g., sum, mean)

Example:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
double_arr = arr * 2  # Vectorized operation
print(double_arr)  # [2 4 6 8 10]


Broadcasting:

Broadcasting is the process of aligning arrays with different shapes to enable element-wise operations. NumPy follows these broadcasting rules:

- If arrays have the same shape, no broadcasting is needed.
- If arrays have different shapes, NumPy tries to broadcast them by:
    - Adding dimensions of size 1 to the smaller array.
    - Repeating the smaller array along the new dimension.

Example:


import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Broadcasting: arr1 is repeated along the new dimension
result = arr1 + arr2[:, np.newaxis]
print(result)  # [[5 6 7], [6 7 8], [7 8 9]]


Contribution to efficient array operations:

Vectorization and broadcasting enable efficient array operations by:

- Avoiding explicit loops, which reduces overhead and improves performance.
- Allowing for parallelization, as operations can be executed simultaneously on multiple elements.
- Enabling the use of optimized, low-level code, which further improves performance.

By leveraging vectorization and broad